// console.dir(document);;
// console.log(document.domain);
// console.log(document.URL);
// console.log(document.title);
// document.title = 'shaik';
console.log(document.getElementById('header'));
header.textcontent = 'hello world';
// console.log(header);
header.innertext = 'hello';
var headerBase = document.getElementById('header');
headerBase.style.borderBottom = 'solid #ccc 3px';
